using ExpenseReports.Application.Abstractions;
using ExpenseReports.Domain.Auditing;
using ExpenseReports.Domain.Employees;
using ExpenseReports.Domain.Expenses;
using ExpenseReports.Domain.Tenants;
using Microsoft.EntityFrameworkCore;

namespace ExpenseReports.Infrastructure.Persistence;

/// <summary>
/// The EF Core unit of work. Its key responsibility beyond mapping is to apply
/// tenant isolation globally, so no individual query has to remember to do it.
/// </summary>
public sealed class ExpenseReportsDbContext : DbContext
{
    // Captured once per context instance (one instance per request). Global
    // query filters compare against it, so every query is tenant-scoped in SQL.
    // If there is no authenticated tenant it stays null and the filters match
    // nothing — the system fails closed rather than leaking data.
    private readonly Guid? _currentTenantId;

    public ExpenseReportsDbContext(DbContextOptions<ExpenseReportsDbContext> options, ITenantProvider tenantProvider)
        : base(options)
    {
        _currentTenantId = tenantProvider.TenantId;
    }

    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<Employee> Employees => Set<Employee>();
    public DbSet<Expense> Expenses => Set<Expense>();
    public DbSet<ExpenseAuditEntry> AuditEntries => Set<ExpenseAuditEntry>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Picks up the per-entity mapping classes (TenantConfiguration, etc.).
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ExpenseReportsDbContext).Assembly);

        // The heart of multi-tenancy: EF Core appends "WHERE TenantId = @current"
        // to every query against these entities, including the ones generated by
        // navigation loading. The filter lives in the SQL, not in the handlers.
        modelBuilder.Entity<Employee>().HasQueryFilter(e => e.TenantId == _currentTenantId);
        modelBuilder.Entity<Expense>().HasQueryFilter(e => e.TenantId == _currentTenantId);
        modelBuilder.Entity<ExpenseAuditEntry>().HasQueryFilter(a => a.TenantId == _currentTenantId);
    }
}
